### ISSUE TITLE
It's unclear from README how to run tests

### ISSUE THREAD

**Issue by yurivict** [pika-org/pika#316]
```-DPIKA_WITH_TESTS=ON``` builds ```libpika_testing.so``` but then ```make test``` says:

> No tests were found!!!

**Comment by msimberg** [comment]
Thanks for pointing this out. I think there are two things going on here:
1. Are you possibly reconfiguring an existing build directory with `-DPIKA_WITH_TESTS=ON`? That option is off by default and disables the sub-categories `PIKA_WITH_TESTS_UNIT` etc. Since we're not using CMake's depndent options they are not reenabled when setting `PIKA_WITH_TESTS=ON`, but you have to individually reenabled the categories. If you do a fresh configuration with `PIKA_WITH_TESTS=ON` they will be automatically enabled. This is just legacy from our side and I've opened an issue to make this change: https://github.com/pika-org/pika/issues/317.
2. Tests always have to be built separately before being run. This is a CMake quirk that we won't work around, but assuming you have tests enabled you'd want to do `make tests && make test`, or more portably `cmake --build . --target tests && ctest`. I've created https://github.com/pika-org/pika/pull/318 to document this in the readme. Could you please comment whether the instructions there would be sufficient for you?

**Comment by yurivict** [comment]
This works, thanks.
Most cmake projects are able to re-configure and build/run tests on top of the pre-built project.
pika is different for some reason.
